### ISSUE TITLE
High pitched RHVoice in the last commit

### ISSUE THREAD

**Issue by zstanecic** [Olga-Yakovleva/RHVoice#180]
Steps to reproduce:
1. Build RHVoice, (platform doesn't matter)
2. after building the new version, install the russian or whatever voice you want,
Current behavior: RHVoice speaks in a high-pitched, deformed voice.
Expected behavior: RHVoice should speak normally
build environment on which this behavior was observed:
win 10, 2004 (20H1), latest visual studio with all respective needed dependencies,.
tested on NVDA 2020.2 and latest alphas.

**Comment by Olga-Yakovleva** [comment]
Can anyone else reproduce this? Perhaps there exist more specific 
conditions related to this problem, as I haven't been able to reproduce 
it myself yet.

**Comment by beqabeqa473** [comment]
yes, i can confirm this.

i tracked down an issue and problem started to appear after merging cmake build system, specifically:
in src/include/core/sample_rate.hpp for some unknown reason
      enum_property<sample_rate_t>("sample_rate",sample_rate_24k)
was changed to
      enum_property<sample_rate_t>("sample_rate",sample_rate_48k)

@KOLANICH what was the reason you touch this part. do you really known what you are doing?

**Comment by KOLANICH** [comment]
I'm sorry.

I have forgotten to revert it after I was testing if higher sample rates work (they don't) and it has leaked into the PR. I have also added a parameter into RHVoice-test to adjust it, but [set it back to 24k](https://github.com/Olga-Yakovleva/RHVoice/pull/135/files#diff-77cffe8341bf99e3beb9f65df6f5eb8bR45) as I realized that they don't work, so in RHVoice-test the issue was masked by the hardcoded default value. In speech_dispatcher module probably somewhere too (since I have not observed that behavior, I mainly use RHVoice via a speech-dispatcher module).

Though I have not tested NVDA and SAPI 5 modules.
