### ISSUE TITLE
Android Application Cant Download Georgian Language(Natia)

### ISSUE THREAD

**Issue by SGamrekelashvili** [Olga-Yakovleva/RHVoice#206]
Application after installing it on Device, it cant download georgian(Natia) Language Pack.
If anyone know any solution right it down ,
Thanks.

**Comment by beqabeqa473** [comment]
sorry for troubles. fixed.

**Comment by SGamrekelashvili** [comment]
Thank you.

**Comment by Olga-Yakovleva** [comment]
@beqabeqa473 could you check your server please? I'm receiving complaints and on my device I seem to have confirmed the problem.

**Comment by beqabeqa473** [comment]
i am sorry for lots of complaints because of this issue. it is
happening quite frequently.
i fixed issue for now, but i will change server configuration in near
future, in next 2-3 days to eliminate this problem Once and for all.

again, sorry for the inconvenience.

On 11/12/20, Olga Yakovleva <notifications@github.com> wrote:
> @beqabeqa473 could you check your server please? I'm receiving complaints
> and on my device I seem to have confirmed the problem.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/206#issuecomment-726174836


-- 
with best regards beqa
