### ISSUE TITLE
репозиторий с deb пакетами

### ISSUE THREAD

**Issue by linvinus** [Olga-Yakovleva/RHVoice#30]
Не баг, 
просто хочу сообщить что сделал репозиторий с пакетами для Ubuntu но должно подойти и для Debian/

https://launchpad.net/~linvinus/+archive/ubuntu/rhvoice/

**Comment by abitrolly** [comment]
@jekhor @andrewshadura а на чём у нас дебианизация застряла?

**Comment by abitrolly** [comment]
@linvinus ты как есть, без патчей собрал?

**Comment by linvinus** [comment]
да, https://launchpad.net/~linvinus/+archive/ubuntu/rhvoice/+files/rhvoice_0.5.1-1linvinus6.debian.tar.xz
только конфиг для speech-dispatcher подложил.

**Comment by andrewshadura** [comment]
@linvinus, можно попросить сделать версию 1~linvinus6? (А эту удалить)

**Comment by andrewshadura** [comment]
Объясню, почему: `~` сортируется до строки без неё, потому когда 0.5.1-1 появится «настоящая» она заменит собой эту, а не наоборот.

**Comment by linvinus** [comment]
ок.

**Comment by abitrolly** [comment]
> потому когда 0.5.1-1 появится «настоящая»

Появится? =)

**Comment by andrewshadura** [comment]
Ну конечно. Времени просто нет. Если хочется, можете заняться пакетировкой MAGE/pHTS, зависимости уже в Дебиане есть.

**Comment by linvinus** [comment]
andrewshadura, MAGE/pHTS,  это что такое?

**Comment by andrewshadura** [comment]
это то, что внутри использует RHVoice.

**Comment by linvinus** [comment]
пакеты перезалил, сновым форматом версий.
так я не понял что ещё запакетировать нужно?

**Comment by andrewshadura** [comment]
@linvinus, в исходниках RHVoice лежит куча вещей (в 3rdparty), которые очень неправильно тянуть в самом пакете. Из них всё уже запакетировано в Debian, кроме [MAGE/pHTS](/numediart/mage).

**Comment by linvinus** [comment]
ок, я пока никакие патчи не накладывал.
расскажите как должно быть? 
может форк nlprocby лучше перевести на правильные рельсы?

**Comment by linvinus** [comment]
вижу вы уже дебианизировали ранее меня :) https://github.com/nlprocby/RHVoice/tree/master/debian

**Comment by andrewshadura** [comment]
Вообще наша дебианизация живёт здесь: https://github.com/minsk-hackerspace/RHVoice/commits/master

**Comment by abitrolly** [comment]
MAGE/pHTS - это работа другой девушки по улучшению времени отклика HMM синтезатора, постороенного на HTS - https://github.com/numediart/mage

**Comment by abitrolly** [comment]
@andrewshadura я утянул в nlprocby, потому что там bindings для Python и пара фиксов с ним связанных.

**Comment by abitrolly** [comment]
> может форк nlprocby лучше перевести на правильные рельсы?

Если ты о том, чтобы его смержить, то см. #21

**Comment by andrewshadura** [comment]
@abitrolly, ну так RHVoice этот MAGE использует.

**Comment by abitrolly** [comment]
> @abitrolly, ну так RHVoice этот MAGE использует.

Ну да, я об этом же - опенсурс - сила. =)

**Comment by abitrolly** [comment]
@andrewshadura а если этот MAGE используется сугубо RHVoice'ом, может это нормально, что он в пакете идёт статически скомпилен? Размер скачиваемого и устанавливаемого от этого не меняется.

**Comment by andrewshadura** [comment]
В том-то и дело, что это самостоятельный софт, который кто-то ещё может хотеть использовать.

**Comment by abitrolly** [comment]
@andrewshadura я сомневаюсь, но ладно. Есть возможность узнать, кто в Debian его уже использует, но не запаковал? Как много там таких проектов? Что делать, если RHVoice использует патченую версию MAGE?

**Comment by andrewshadura** [comment]
Сложно сказать. Если использует патченую, нужно выяснить, насколько патченую, по возможности патчи заапстримить, если они не ломают остальные проекты, возможно, некоторое время иметь их в дистрибутивном пакете, но не в апстриме.

**Comment by andrewshadura** [comment]
Вот например, rhvoice использует старую версию hts engine с другим API, а порт на новую версию ещё не смержен, потому hts engine я буду бандлить, но потом вынесу, когда патч приземлится в мастере.

**Comment by Voskrese** [comment]
спасибо за проделанную работу
а то не осилил сборку по линукс, RHVoice: команда не найдена
с https://launchpad.net/~linvinus/+archive/ubuntu/rhvoice/+packages
все ок

**Comment by abitrolly** [comment]
Для начала надо HTS забандлить. Есть вероятность, что он станет весьма популярным в ближайшие годы. =)

**Comment by andrewshadura** [comment]
pHTS или HTS engine? Т.к. тот второй есть, а первый уже не нужен :)

**Comment by KOLANICH** [comment]
Since CMake building and packaging has landed, it may make sense to combine debianization files (machine-readable copyright info, manpages, etc) into it and then to try to make the packages official.

**Comment by abitrolly** [comment]
@KOLANICH is CMake something that Debian requires for official packages? I don't see the connection.

**Comment by andrewshadura** [comment]
@abitrolly, I guess the point was that CMake can generate .debs. Which is irrelevant to getting it into Debian proper.

**Comment by andrewshadura** [comment]
I’m willing to look at packaging again; I don’t have much personal incentive, but why not — if I find enough time :slightly_smiling_face:

**Comment by KOLANICH** [comment]
>is CMake something that Debian requires for official packages? I don't see the connection.

The connection is that I have written the code splitting rhvoice into packages in CMake. The packages are built using CPack. Not only for Debian-based distros. It is waste to use debhelper for this. So I propose to add the debianization files to this repo and build packages for debian using the metadata defined in CMake.

**Comment by andrewshadura** [comment]
CPack is not an acceptable solution to package anything for any distribution. SCons is good enough a build system, and a native distribution’s tools should be used for each distro.

**Comment by abitrolly** [comment]
@KOLANICH DRY principle applied here would be to learn Python, which is the language in which NVDA written. :D Then instead of adding another dependency, you could actually commit SCons to this repo, to help people avoid installing anything at all.

**Comment by KOLANICH** [comment]
I don't need nvda, I am not blind.

**Comment by zstanecic** [comment]
But users of this synth are blind, at least some of them.

Don’t be selfish.

**Comment by KOLANICH** [comment]
Yes, I know. But assisting technology for visually impaired people is not the only use case of such tools. Answering machines, voice-controlled assistants, notifications about events at distance, automatic dubbing of movies ... the applications are limitless. You should not assumme that everyone needs that NVDA. NVDA is a very niche use case.

**Comment by zstanecic** [comment]
I know. 

Me myself use NVDA, as I am a blind RHVoice user. I am using RHVoice to read Russian.

**Comment by abitrolly** [comment]
@KOLANICH as far as I've heard, Olga is NVDA user and wrote the library to solve the specific accessibility problem in this niche. I can't blame you for not knowing, because the story is not covered by the media.

**Comment by KOLANICH** [comment]
I understand. But it doesn't mean that if NVDA is written in python or uses scons, this project must too. This project is not just a plugin for NVDA. It is a general purpose speech synthesizer. A free open source one. Most of other ones are either proprietary and maybe costly  or maybe server side or just early prototypes in python + TensorFlow unsutable for use - they have no "standardized" interfaces (such as SAPI 5 and Speech Dispatcher) and cannot be plugged into any software supporting the standard.

So what build systems nvda uses and in which language it is written is completely irrelevant here. This project is not a part of NVDA project.

**Comment by zstanecic** [comment]
It is relevant, because maybe you as a contributor in the future want to drop NVDA support.

What is irrelevant for you, it doesn’t mean that it is irrelevant for others. 

Simple, fair and straightforward…

**Comment by KOLANICH** [comment]
>the story is not covered by the media.

I know that Olga is blind. I have read about it on Habr not so long ago. https://habr.com/ru/company/ruvds/blog/511236/ Anyway, I know that there are people who were unfortunate enough to be  blind, and that they use speech synhesizers to be able to use PC. I also deeply respect Olga because she has knowledge and skills I don't have. I.e. I don't understand how tools of this kind (non-neural with lot of handcode) work and how to craft an own one. But it still doesn't mean that users of the tool must care of the build systems used by NVDA or that the tool must depend on NVDA anyhow. The same reasoning as with python: if I don't need python, why do I need it (i know there are comparatively small distros of python, but they still unpack too slow) on my PC? If I don't need NVDA, why do I need its pieces on my PC (I know I don't need, but the rhetorics in this thread "а вот NVDA..." ... noone who doesn't need NVDA cares about it, and they have one simple question ... why should they care about it if they don't need it)?

**Comment by zvezdochiot** [comment]
@KOLANICH say:
>С каких это пор контрибьютерам позволяют такие решения принимать?

Лицензия вроде не запрещает. Более того, патчи вполне разрешены и эксплуатируются повсеместно.

**Comment by KOLANICH** [comment]
The license doesn't forbid forks. But the decisions about the fork are up to fork maintainer. The decisions about the project are the decisions about its "main fork" called "upstream". This repo is upstream. And its  Olga its

**Comment by zvezdochiot** [comment]
Привет @KOLANICH .

Возможно я не до конца понял, но мне показалось, что речь идёт за конкретные сборки. И здесь дела обстоят несколько по-другому. Многие дистры вносят спецпатчи для сборок. Я это знаю точно, так как сам вносил такие патчи для сборок в Debian Wheezy.

**Comment by KOLANICH** [comment]
If distro-specific patches are not upstreamed, it is either laziness or circumstances of package maintainers of subborness of upstream maintainers or both. IMHO - it almost always make sense to upstream distro-specific patches, but it is not always possible - either upstream says "I don't need your patches, your patches implement a feature, completely unneeded for everyone except of you", or the upstream says "I need you patches, but you have to reingeneer them to be more universal" ... but the package maintainer cannot do that, i.e. because the he is not enough familiar with the technology used (in my case it was autotools) and has no will to learn it because the technology is damn legacy or other piece of shit or the package maintainer has no time or other reasons.

IMHO - the packages for distros should be built from vanilla code got directly from the upstream. Patches is a drastic measure when the upstam and the package maintainer have not come to consensus. Patches require constant human attention because the upsteam is not aware of them and doesn't care of them, and go broken any time. They are too costly to maintain and the result is that the distros have necro-versions of the software.
