### ISSUE TITLE
rewrite build scripts into cmake

### ISSUE THREAD

**Issue by KOLANICH** [Olga-Yakovleva/RHVoice#88]
scons is not the best choice. Not everyone has python and not everyone want to install it on a Windows machine. CMake is more lightweight, universal and with minimum dependencies.

**Comment by paulvi** [comment]
@KOLANICH If you know cmake tool, you are possibly the first to do it.

2 build tool can coexist for some time.

**Comment by KOLANICH** [comment]
@paulvi, I have some experience with CMake, but I don't have time for now to work on this issue.

**Comment by waruqi** [comment]
Also consider using other build systems, such as: https://github.com/tboox/xmake 😄

**Comment by abitrolly** [comment]
@paulvi these are arguments **against spending precious developers time on CMake integration**. If you tell me that it is not possible to contribute, because SCons doesn't work on your system to build project - that's an argument. If there is a PR with the transition to try CMake in a branch - that's an argument. If you tell me to stop telling bad things about `cmake` because you love it, and don't want to learn anything else, then sorry. I love SCons and won't allow you to get rid of it without some serious debate and bikeshedding. :D

I actually was wrong about Bazel. The system that gets all the hype is Meson. `systemd` and GNOME switched to it, but OMG - you won't like it - it is Python too! Mind you that NVDA plugin is written in Python. Here are some comparisons - https://mesonbuild.com/Comparisons.html#cmake

**Comment by starsnet** [comment]
for example, my operation system have not ldconfig-command (for SCons) and have not systemd.
what should I do ?)

**Comment by abitrolly** [comment]
@starsnet these are is not a part of SCons, therefore there is a high risk that after rewriting this to CMake you will just waste time and won't fix the problem with `systemd` and `ldconfig` on your system. If you know how to fix this problem without build system, then fixing it with SCons would be easier than fixing it with CMake, because Python.

**Comment by starsnet** [comment]
> @abitrolly these are is not a part of SCons, therefore there is a high risk that after rewriting this to CMake you will just waste time and won't fix the problem with `systemd` and `ldconfig` on your system. If you know how to fix this problem without build system, then fixing it with SCons would be easier than fixing it with CMake, because Python.

python - evil))

**Comment by starsnet** [comment]
C/C++ or LISP )

**Comment by abitrolly** [comment]
@starsnet Haskel! :D
